#!/usr/bin/env node
/**
 * A command-line client for bench testing Decentralized Identifier Networks.
 *
 * Copyright (c) 2019 Digital Bazaar, Inc. All rights reserved.
 */

 const {startOperations} = require('./lib');

 const hostnames = [{hostname: 'genesis.veres.one.localhost:42443'}]
 startOperations({hostnames, operationsPerSecond: 1000})
